/* ============================================================================
 *  Crypto Random
 *  --------------------------------------------------------------------------
 *  @file    random.h
 *  @brief   Cryptographically secure random bytes, hex tokens, and unbiased
 *           bounded integers over OpenSSL's CSPRNG.
 *  @author  CFW
 *  @date    2026-08-08
 *  @license MIT (see LICENSE file)
 *
 *  A framework-native wrapper around OpenSSL's RAND_bytes. This is the ONLY
 *  sanctioned source of security-grade randomness in CFW: session tokens,
 *  password salts, CSRF tokens, trace ids, nonces. The `random/` module
 *  (PCG32) is deterministic by design and must never be used for secrets.
 *
 *  Features:
 *    - crypto_random_bytes: fail-closed CSPRNG fill of a caller buffer.
 *    - crypto_random_hex: lowercase-hex token straight into a caller buffer.
 *    - crypto_random_uniform: unbiased bounded draw (rejection sampling, no
 *      modulo bias).
 *
 *  Usage Examples:
 *    @code
 *    #include <char/char.h>                // CHAR_END_CHARACTER
 *    #include <crypto/random/random.h>
 *
 *    char token[CRYPTO_RANDOM_HEX_SIZE(32) + CHAR_END_CHARACTER] = DEFAULT_INITIALIZATION;
 *
 *    if (result_is_error(crypto_random_hex(token, 32))) {
 *        return false; // fail closed: no token issued
 *    }
 *    @endcode
 *
 *  Error Handling:
 *    - Functions return RESULT_SUCCESS, or RESULT_CATEGORY_LIBRARY when the
 *      OpenSSL CSPRNG reports failure (the OpenSSL error text is captured, the
 *      thread's OpenSSL error queue is drained — a caller's own later
 *      ERR_get_error sees nothing — and the failure is logged with that text);
 *      the output buffer contents are then unspecified and must not be used
 *      (fail closed).
 *    - A zero size/bound, or a byte_count too large for CRYPTO_RANDOM_HEX_SIZE
 *      to represent, returns RESULT_CATEGORY_ARGUMENT instead of aborting:
 *      sizes here may someday derive from request input, and a secret-issuing
 *      path must fail closed rather than crash — a zero-byte "success" would
 *      be an empty secret.
 *    - Required pointer arguments are validated first; a null argument aborts
 *      via error_check_null when ERROR_CHECK_ENABLED is defined. With
 *      ERROR_CHECK_ENABLED undefined the null checks compile out and a null
 *      pointer is undefined behaviour; the zero/oversize refusals above are
 *      value branches that hold in every build regardless.
 *
 *  Thread Safety:
 *    - Stateless; every function is safe to call concurrently (OpenSSL's
 *      CSPRNG is internally thread-safe).
 *
 *  Memory Management:
 *    - No heap allocation. The caller owns every buffer; crypto_random_hex
 *      needs CRYPTO_RANDOM_HEX_SIZE(byte_count) + 1 chars.
 *    - crypto_random_hex copies the generated bytes into a private stack
 *      chunk before hex-encoding it; that chunk is not zeroised on return.
 *      CFW has no memory_wipe yet, so a caller that must erase a token
 *      scrubs its own output buffer.
 *
 *  Performance Characteristics:
 *    - O(n) in the requested byte count. crypto_random_uniform draws 8 bytes
 *      per attempt and rejects with probability < 1/2 per round.
 *    - Requests above INT_MAX bytes are filled in INT_MAX-sized chunks
 *      internally (RAND_bytes takes an int length); the size is never
 *      narrowed or truncated, only chunked.
 *
 *  Dependencies (Deps):
 *    - OpenSSL (<openssl/rand.h>, <openssl/err.h>) — RAND_bytes and
 *      ERR_error_string_n are 1.0-era APIs; this module sets no version
 *      floor beyond what the build already requires, unlike crypto/hmac's
 *      >= 3.0 floor.
 *    - encoding/hex (hex.h — chains error → tracelog → log → thread, which
 *      provide limits.h and types.h).
 *    - result.h, included directly so the header compiles standalone.
 * ============================================================================
 */
#ifndef CRYPTO_RANDOM_H
#define CRYPTO_RANDOM_H

#include <openssl/err.h>
#include <openssl/rand.h>

#include <result.h>
#include <encoding/hex/hex.h>

/*==============================================================================
 * MARK: - Macros
 *============================================================================*/

#define CRYPTO_RANDOM_HEX_SIZE(byte_count) ENCODING_HEX_SIZE(byte_count) /**< Hex chars for byte_count random bytes (excl. NUL). */

/*==============================================================================
 * MARK: - Public Functions
 *============================================================================*/

/**
 * @brief Fill a buffer with cryptographically secure random bytes.
 * @param output Destination buffer; filled entirely on success.
 * @param size   Number of bytes to generate.
 * @return RESULT_SUCCESS; RESULT_CATEGORY_ARGUMENT when size is zero;
 *         RESULT_CATEGORY_LIBRARY on CSPRNG failure (output contents are
 *         then unspecified — fail closed).
 */
CFW_ATTR_NODISCARD
Result crypto_random_bytes(U8 *const output, USize const size);

/**
 * @brief Write a lowercase-hex token of byte_count random bytes.
 * @param output     Destination; must hold CRYPTO_RANDOM_HEX_SIZE(byte_count) + 1
 *                   chars. NUL-terminated on success.
 * @param byte_count Number of random bytes to draw.
 * @return RESULT_SUCCESS; RESULT_CATEGORY_ARGUMENT when byte_count is zero or
 *         exceeds (USIZE_MAX - 1) / 2; RESULT_CATEGORY_LIBRARY on CSPRNG
 *         failure (output contents are then unspecified — fail closed).
 */
CFW_ATTR_NODISCARD
Result crypto_random_hex(char *const output, USize const byte_count);

/**
 * @brief Draw an unbiased uniform integer in [0, bound).
 * @param bound Exclusive upper bound.
 * @param value Receives the drawn value on success; untouched on failure.
 * @return RESULT_SUCCESS; RESULT_CATEGORY_ARGUMENT when bound is zero;
 *         RESULT_CATEGORY_LIBRARY on CSPRNG failure.
 */
CFW_ATTR_NODISCARD
Result crypto_random_uniform(U64 const bound, U64 *const value);

#endif // CRYPTO_RANDOM_H